# Generated by Django 4.2.13 on 2024-06-28 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDF_File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('pdf_file', models.FileField(upload_to='Files')),
                ('audio', models.FileField(blank=True, null=True, upload_to='Audio')),
            ],
            options={
                'verbose_name': 'PDF_File',
                'verbose_name_plural': 'PDF_Files',
            },
        ),
    ]
