# Generated by Django 4.2.13 on 2024-06-28 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Audiofiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf_file',
            name='extract',
            field=models.TextField(blank=True, null=True),
        ),
    ]
